spring:
  datasource:
    url: jdbc:h2:mem:codesquadpost
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true           # H2 Console 사용 여부
      path: /h2-console       # H2 Console 접속 주소

logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace
